/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devhw12;

import com.google.gson.Gson;

import java.util.HashMap;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Map<String, String> person = new HashMap<>();
        person.put("firstname", "Eugen");
        person.put("lastname", "Stoliarenko");
        person.put("lastname1", "Stoliarenko1");
        System.out.println(new Gson().toJson(person));

    }
}
